INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (1, 'Running Shoes', 'Footwear', 'Nike', 120, 9999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (2, 'Smartphone', 'Electronics', 'Samsung', 80, 24999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (3, 'Laptop', 'Electronics', 'Dell', 40, 55999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (4, 'Bluetooth Headphones', 'Electronics', 'Sony', 150, 6999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (5, 'Smart Watch', 'Wearable', 'Apple', 60, 34999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (6, 'LED TV', 'Electronics', 'LG', 30, 45999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (7, 'Refrigerator', 'Appliances', 'Whirlpool', 25, 38999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (8, 'Washing Machine', 'Appliances', 'Bosch', 20, 42999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (9, 'Microwave Oven', 'Appliances', 'IFB', 35, 18999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (10, 'Air Conditioner', 'Appliances', 'Daikin', 18, 52999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (11, 'Office Chair', 'Furniture', 'Godrej', 90, 7999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (12, 'Study Table', 'Furniture', 'Ikea', 70, 11999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (13, 'Sofa Set', 'Furniture', 'Urban Ladder', 15, 65999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (14, 'Men T-Shirt', 'Clothing', 'Puma', 200, 1499);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (15, 'Women Jeans', 'Clothing', 'Levis', 180, 2999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (16, 'Mixer Grinder', 'Kitchen', 'Philips', 75, 4599);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (17, 'Electric Kettle', 'Kitchen', 'Havells', 140, 1999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (18, 'Cricket Bat', 'Sports', 'SG', 90, 3999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (19, 'Dumbbell Set', 'Fitness', 'Aurion', 50, 5999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (20, 'Face Wash', 'Personal Care', 'Nivea', 220, 299);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (21, 'Shampoo', 'Personal Care', 'Loreal', 190, 699);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (22, 'Notebook', 'Stationery', 'Classmate', 300, 120);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (23, 'Ball Pen', 'Stationery', 'Reynolds', 500, 20);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (24, 'Power Bank', 'Electronics', 'Mi', 160, 1999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (25, 'Router', 'Networking', 'TP-Link', 55, 3299);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (26, 'Printer', 'Electronics', 'HP', 25, 15499);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (27, 'External Hard Disk', 'Electronics', 'Seagate', 70, 6499);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (28, 'USB Flash Drive', 'Electronics', 'SanDisk', 180, 899);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (29, 'DSLR Camera', 'Photography', 'Canon', 15, 54999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_BRAND, PRODUCT_STOCK_QUANTITY, PRODUCT_PRICE)
VALUES (30, 'Tripod Stand', 'Photography', 'Digitek', 65, 1999);
